export const cityLocation = [
    'Angeles City',
    'Apalit',
    'Arayat',
    'Bacolor',
    'Basa airbase',
    'Candaba',
    'Floridablanca',
    'Guagua',
    'Lubao',
    'Mabalacat',
    'Macabebe',
    'Magalang',
    'Masantol',
    'Mexico',
    'Minalin',
    'Porac',
    'San Fernando',
    'San Luis',
    'San simon',
    'Sexmoan',
    'Sta. Ana',
    'Sta. Rita',
    'Sto. Tomas',
]